### ISSUE TITLE
Ukrainian translate

### ISSUE THREAD

**Issue by JuriyCherednichock** [orthanc-server/orthanc-explorer-2#17]
{
    "all_modalities": "всі",
    "anonymize": "Анонімізувати",
    "cancel": "Скасувати",
    "change_password": "Змінити пароль",
    "close": "Закрити",
    "copy_orthanc_id": "Копіювати Orthanc ID",
    "date_picker": {
        "today" : "Сьогодні",
        "yesterday": "Вчора",
        "this_week": "Цього тижня",
        "last_week": "Минулого тижня",
        "this_month": "Цього місяця",
        "last_month": "Минулого місяця",
        "last_12_months": "За останні 12 місяців"
    },
    "default": "За замовчуванням",
    "delete": "Видалити",
    "delete_study_title": "Видалити дослідження?",
    "delete_study_body": "Ви впевнені, що хочете видалити це дослідження?<br/>Цю дію не можна скасувати!",
    "delete_studies_title": "Видалити дослідження?",
    "delete_studies_body": "Ви впевнені, що хочете видалити ці дослідження?<br/>Цю дію не можна скасувати!",
    "delete_series_title": "Видалити серії?",
    "delete_series_body": "Ви впевнені, що хочете видалити ці серії?<br/>Цю дію не можна скасувати!",
    "delete_instance_title": "Видалити інстанс (екземпляр)?",
    "delete_instance_body": "Ви впевнені, що хочете видалити цей інстанс (екземпляр)?<br/>Цю дію не можна скасувати!",
    "description": "Опис",
    "dicom_AET": "DICOM AE Title",
    "dicom_modalities": "Модальності DICOM",
    "dicom_port": "Порт DICOM",
    "dicom_web_servers": "Сервери DICOM-Web",
    "dicom_tags" : {
        "seriesCount": "Кількість серій",
        "AccessionNumber": "Номер обстеження",
        "BodyPartExamined": "Обстежена частина тіла",
        "InstanceNumber": "Номер інстансу (екзкмпляру)",
        "InstitutionName": "Назва установи",
        "Modality": "Модальність",
        "ModalitiesInStudy": "Модальності у дослідженні",
        "NumberOfFrames": "Кількість кадрів",
        "NumberOfStudyRelatedSeries": "Кількість серій, пов'язаних із дослідженням",
        "NumberOfStudyRelatedInstances": "Кількість інстансів (екземплярів), пов'язаних із дослідженням",
        "PatientBirthDate": "Дата народження пацієнта",
        "PatientID": "ID пацієнта",
        "PatientName": "Ім'я пацієнта",
        "PatientSex": "Стать пацієнта",
        "ProtocolName": "Назва протоколу",
        "ReferringPhysicianName": "Призвище лікаря, що направив",
        "RequestingPhysician": "Лікар, що робить запит",
        "SeriesDate": "Дата серій",
        "SeriesDescription": "Опис серій",
        "SeriesInstanceUID": "UID інстансу (екземпяру) серії",
        "SeriesNumber": "Номер серії",
        "SeriesTime": "Час серії",
        "StudyDate": "Дата дослідження",
        "StudyDescription": "Опис дослідження",
        "StudyID": "ID дослідження",
        "StudyTime": "Час дослідження",
        "SOPInstanceUID": "UID SOP-інстансу (екземпляру)",
        "StudyInstanceUID": "UID інстансу (екземпяру) дослідження"
    },
    "displaying_latest_studies": "Відображення останніх досліджень",
    "download_dicom_file": "Завантажити файл DICOM",
    "download_dicomdir": "Завантажити DICOMDIR",
    "download_zip": "Завантажити ZIP архів",
    "drop_files": "Перетягніть файли сюди або",
    "enter_search": "Введіть критерії пошуку аби відобразити результати!",
    "error": "Помилка)",
    "file": "Файл",
    "files": "файли",
    "frames": "кадри",
    "ingest_transcoding": "Транскодування даних, що надходять",
    "installed_plugins": "Встановлені додатки (плагіни)",
    "instance": "Інстанс (екземпляр)",
    "instances_number": "Кількість інстансів (екземплярів)",
    "instances": "Інстанси (екземпляри)",
    "labels" : {
        "add_button": "Додати",
        "add_labels_message_html": "<strong>Додати</strong> ці мітки усім вибраним ресурсам resources",
        "add_labels_placeholder": "Мітки, що будуть додані; натисність Enter для створення нової",
        "added_labels_message_part_1_html": "Додані мітки ",
        "added_labels_message_part_2_html": " до <strong>{count}</strong> досліджень",
        "clear_all_button": "Видалити все",
        "clear_all_labels_message_html": "<strong>Видалити всі</strong> мітки у всіх виділених ресурсах",
        "cleared_labels_message_part_1_html": "Видалені мітки ",
        "cleared_labels_message_part_2_html": " з <strong>{count}</strong> досліджень",
        "edit_labels_button": "Редагувати мітки",
        "modal_title": "Редагування міток у виділених ресурсах",
        "remove_button": "Видалити",
        "remove_labels_message_html": "<strong>Видалити</strong> ці мітки з усіх вибраних ресурсів",
        "remove_labels_placeholder": "Мітки, що будуть вилучені",
        "removed_labels_message_part_1_html": "Видалені мітки ",
        "removed_labels_message_part_2_html": " з <strong>{count}</strong> досліджень"
    },
    "legacy_ui": "Старий інтерфейс",
    "loading_latest_studies": "Завантаження останніх досліджень",
    "local_studies": "Усі локальні дослідження",
    "logout": "Вихід",
    "modalities_in_study": "Модальності у дослідженні",
    "modify": {
        "anonymize_button_title": "Анонімізувати",
        "anonymize_modal_title": "Анонімізувати",
        "autogenerated_dicom_uid": "Автоматично згенеровані",
        "back_button_title": "Взад",
        "error_attach_series_to_existing_study_target_does_not_exist_html": "Помилка під час зміни серії, дослідження з цим StudyInstanceUID не знайдено.",
        "error_attach_series_to_existing_study_target_unchanged_html": "Помилка під час зміни серії, цільове дослідження таке ж, як поточне дослідження серії.",
        "error_attach_study_to_existing_patient_target_does_not_exist_html": "Помилка під час зміни пацієнта, пацієнта з цим ID пацієнта не знайдено. Можливо, замість цього вам слід скористатися функцією <strong>Змінити теги дослідження</strong>.",
        "error_modify_any_study_tags_patient_exists_html": "Помилка під час зміни тегів дослідження: уже існує інший пацієнт із таким самим ID пацієнта. Замість цього слід скористатися функцією <strong>Змінити пацієнта</strong>.",
        "error_modify_any_study_tags_can_not_modify_patient_tags_because_of_other_studies_html": "Помилка під час зміни тегів дослідження: цей пацієнт має інші дослідження. Замість цього слід використовувати функцію <strong>Змінити теги пацієнта</strong>.",
        "error_modify_patient_tags_another_patient_exists_with_same_patient_id_html": "Помилка під час зміни тегів пацієнта: уже існує інший пацієнт із таким самим ID пацієнта. Замість цього слід використовувати функцію <strong>Змінити теги пацієнта</strong>.",
        "error_modify_unexpected_error_html": "Неочікувана помилка під час модифікації, час перевірити логи Orthanc",
        "insert_tag": "Вставити тег DICOM",
        "job_in_progress": "Модифікація обробляється",
        "modify_mode_new_uids_html": "Модифікація оригінального дослідженя.  <small>(генерація нових DICOM UIDів)</small>",
        "modify_mode_keep_uids_html": "Модифікація оригінального дослідженя.  <small>(лишаємо оригінальні DICOM UIDи)</small>",
        "modify_mode_duplicate_html": "Створюємо модифіковану копію дослідження.  <small>(генеруємо нові DICOM UIDи ТА лишаємо оригінальне дослідження)</small>",
        "modify_button_title": "Модифікувати",
        "modify_modal_title": "Модифікувати",
        "remove_tag_tooltip": "Видалити тег",
        "remove_tag_undo_tooltip": "Відмінити видалення тегу",
        "show_modified_resources": "Показати модифіковані ресурси",
        "series_step_0_attach_series_to_existing_study_html": "Перемістіть цю серію до наявного дослідження.",
        "series_step_0_attach_series_to_existing_study_button_title_html": "Змінити дослідження",
        "series_step_0_create_new_study_html": "Перенесіть цю серію до нового дослідження.",
        "series_step_0_create_new_study_button_title_html": "Створити нове дослідження",
        "series_step_0_modify_series_html": "Модифікати теги серії лише у цій серії ?",
        "series_step_0_modify_series_button_title_html": "Модифікувати теги серії",
        "study_step_0_attach_study_to_existing_patient_html": "Приєднайте це дослідження до іншого наявного пацієнта.",
        "study_step_0_attach_study_to_existing_patient_button_title_html": "Змінити пацієнта",
        "study_step_0_patient_has_other_studies_html": "Загальна кількість досліджень цього пацієнта: <strong>{count}</strong>.<br/>Ви бажаєте змінити пацієнта в усіх цих дослідженнях ?",
        "study_step_0_patient_has_other_studies_button_title_html": "Змінити теги пацієнта",
        "study_step_0_modify_study_html": "Змінити теги пацієнта/дослідження лише в цьому дослідженні ?",
        "study_step_0_modify_study_button_title_html": "Змінити теги дослідження",
        "warning_create_new_study_from_series_html": "Пацієнт із таким самим ID пацієнта уже існує з різними тегами. Чи бажаєте ви використовувати існуючі Ім'я пацієнта, стать пацієнта і дату народження пацієнта?"
    },
    "my_jobs": "Мої завдання",
    "no_result_found": "Результатів немає!",
    "no_modalities": "Нічого",
    "not_showing_all_results": "Не показано всі результати. Ви повинні уточнити критерії пошуку",
    "open": "Відкрити",
    "orthanc_name": "Orthanc Name",
    "orthanc_system_info": "Orthanc System Info",
    "orthanc_version": "Orthanc Version",
    "overwrite_instances": "Перезаписати інстанси (екземпляри)",
    "page_not_found": "Нема такої сторінки!",
    "plugin": "додаток (плагін)",
    "plugins_not_enabled": "Завантажені додатки (плагіни) які не ввімкнені або некоректно налаштовані ",
    "preview": "Попередній перегляд",
    "profile": "Профіль",
    "retrieve_and_view": {
        "finding_locally": "Перевірка наявності дослідження на місці.",
        "finding_remotely": "Пошук дослідження у віддалених DICOM нодах.",
        "not_found": "Дослідження не було знайдено ні локально, ні у віддалених DICOM нодах.",
        "retrieving": "Отримання дослідження.",
        "retrieved_html": "Отримано <strong>{count}</strong> інстансів (екземплярів)." 
    },
    "searching": "Пошук...",
    "select_files": "Виберіть файли",
    "select_folder": "Виберіть теку",
    "send_to": {
        "button_title": "Надіслати",
        "orthanc_peer": "Надіслати до Orthanc піру",
        "dicom": "Надіслати до DICOM ноди",
        "dicom_web": "Надіслати до DICOMWeb серверу",
        "transfers": "Надіслати до Orthanc Peer (advanced-transfers)"
    },
    "series_count_header": "# серій",
    "series": "Серії",
    "series_plural": "Серії",
    "settings": "Налаштування",
    "share": {
        "anonymize": "Анонімізувати?",
        "button_title": "Поділитись",
        "copy_and_close": "Копіювати та закрити",
        "days": "дні",
        "expires_in": "Термін дії закінчується через",
        "link": "Посилання",
        "modal_title": "Поділитись дослідженням",
        "never": "ніколи"
    },
    "show_errors": "Показати помилки",
    "statistics": "Статистика",
    "storage_compression": "Стиснення сховища",
    "storage_size": "Розмір сховища",
    "striked_through": "закреслений",
    "studies": "Дослідження",
    "study": "Дослідження",
    "this_patient_has_other_studies" : "У цього пацієнта загалом {count} досліджень.",
    "this_patient_has_no_other_studies" : "У цього пацієнта немає більше досліджень.",
    "this_patient_has_other_studies_show" : "Показати їх !",
    "token" : {
        "token_being_checked_html": "Ваш токен перевіряється.",
        "error_token_invalid_html": "Ваш токен недійсний.<br/>Перевірте, чи вставили його повністю, або зверніться до особи, яка вам його надала.",
        "error_token_expired_html": "Ваш токен протермінований.",
        "error_token_unknown_html": "Ваш токен недійсний.<br/>Перевірте, чи вставили його повністю, або зверніться до особи, яка вам його надала."
    },
    "trace": "Трасування",
    "upload": "Завантажити",
    "uploaded_studies": "Завантажені дослідження",
    "verbose": "Докладно",
    "verbosity_level": "Рівень докладності",
    "view_in_meddream": "Подивитись у MedDream",
    "view_in_ohif": "Подивитись у OHIF",
    "view_in_ohif_vr": "Подивитись у OHIF Volume Rendering mode",
    "view_in_ohif_tmtv": "Подивитись у OHIF Total Metabolic Tumor Volume mode",
    "view_in_osimis": "Подивитись у OsimisViewer",
    "view_in_stone": "Подивитись у StoneViewer",
    "view_in_volview": "Подивитись у VolView"    
}

**Comment by JuriyCherednichock** [comment]
[uk-UA.json.zip](https://github.com/orthanc-server/orthanc-explorer-2/files/11801087/uk-UA.json.zip)

**Comment by amazy** [comment]
Thanks, I have included your changes in this commit: https://github.com/orthanc-server/orthanc-explorer-2/commit/5f5eaa5217581fc79a7354b2899639d91e248409
