### ISSUE TITLE
Should we add "SOP Instance UID" as a localizable value?

### ISSUE THREAD

**Issue by Maksym-Kozub** [orthanc-server/orthanc-explorer-2#27]
Earlier today, I noticed that in uk.json, there was a line (#58) for "SOPInstanceUID" with Ukrainian version of the value. I saw that there is no such asset in en.json, and removed it from uk.json. @amazy merged my commit into master. However, now I see that in series details for studies in the database, there is a "SOP Instance UID"column, its title remaining the same (i.e. English) in all language versions. Probably there used to be such localizable asset before, but it was removed (maybe just by mistake?) later. Should we bring it back to the English version, so that I will be able to localize it again into Ukrainian, and other translators and/or developers will be able to provide it in those other languages, like we have it e.g. with "StudyInstanceUID"?

**Comment by amazy** [comment]
I added it back: https://github.com/orthanc-server/orthanc-explorer-2/commit/ee2f883ed22c72e55202c0b0dd81dee0c6c2004f
However, to me, that's the kind of technical tag that does not really deserve a translation.

**Comment by Maksym-Kozub** [comment]
> However, to me, that's the kind of technical tag that does not really deserve a translation.

I get your point, but I think it is logical to apply some common policy to all technical tags: if we translate e.g. "Series Instance UID", then we should also translate "SOP Instance UID", shouldn't we? Either this way, or we don't translate any of those, but I prefer the first option :).
