### ISSUE TITLE
German language file

### ISSUE THREAD

**Issue by davehuppe** [orthanc-server/orthanc-explorer-2#31]
[de.json.txt](https://github.com/orthanc-server/orthanc-explorer-2/files/12515517/de.json.txt)
I had ChatGPT do the translation for the German language.
At first glance, it looks very good.
If something does not fit, this can be handle with additional issue reports.

**Comment by amazy** [comment]
Thanks !
This has been included in [this commit](https://github.com/orthanc-server/orthanc-explorer-2/commit/8748fc45c3e43bd58466e5b80de6eccd14fc310b) and will be available in the next release.
