### ISSUE TITLE
Responses for few APIs are quite slow.

### ISSUE THREAD

**Issue by selvesandev** [orthanc-server/orthanc-explorer-2#32]
We upgraded our PACs to the newly available image osimis/orthanc:23.8.2. The metadata API is working awesomely. This API is sprinting after the update, which was quite slow before. :slight_smile:

However, after the update to this new version, we found a few APIs acting quite slow which was working fine before.

```
/dicom-web/studies/26141504030405000200283019/series/1.2.276.0.7230010.3.1.3.2692228702.4164.1694812049.374/instances/1.2.276.0.7230010.3.1.4.2692228702.4164.1694812049.372/bulk/00480105/1/00282000
```

For eg, this particular API is very slow with reference to the size of it's response. Check out the below screenshot: a response size of 3.1 KB is taking 25 seconds to load, while the metadata API, which has a size of 553 KB, is taking 2.39 seconds.

![image](https://github.com/orthanc-server/orthanc-explorer-2/assets/21096850/27930094-11ec-48cc-bf57-049511130ec4)

![image](https://github.com/orthanc-server/orthanc-explorer-2/assets/21096850/27462c70-f013-4222-87b6-50bf343d8a3d)

Thank you,
Selvesan Malakar

**Comment by amazy** [comment]
Closing since not related to Orthanc Explorer 2.  See https://discourse.orthanc-server.org/t/postgresql-mysql-5-1-dicomweb-1-14-performance-improvements/3685/6
