### ISSUE TITLE
Do want to have Bulgarian translation

### ISSUE THREAD

**Issue by isheo36** [orthanc-server/orthanc-explorer-2#44]
Hello I can make Bulgarian translation. If you want write me and I will.

**Comment by amazy** [comment]
Hi @isheo36 

Personally, I don't need it.  But if you or any Bulgarian user consider it useful, feel free to provide me with these translations.
All you need to do is provide a file like [this one](https://github.com/orthanc-server/orthanc-explorer-2/blob/master/WebApplication/src/locales/en.json) (only modify the texts on the right part of the `:`).

Best regards,

Alain.

**Comment by amazy** [comment]
closing the issue due to inactivity
