### ISSUE TITLE
Dev mode not working

### ISSUE THREAD

**Issue by crocy** [orthanc-server/orthanc-explorer-2#47]
Hey, I'd like to develop a new feature (share a link via email or even SMS) but I can't get the dev mode to work. I followed the instructions as such:
- installed Orthanc via `sudo apt install orthanc`
  - this also started the server with default config and it's working fine on the `http://localhost:8042/` URL
- then I cloned this `orthanc-explorer-2` repo
- `cd` to repo and ran `apt install nginx`
- than ran
  ```
  cd WebApplication
  npm install
  npm run dev
  ```
  in one console
- since my Orthanc server is running on default port 8042, I updated the line 32 in `scripts/nginx-dev.conf` to `set $orthanc 'http://127.0.0.1:8042';` to the correct port and then ran `sudo ./scripts/start-nginx.sh` in the other console
- if I now visit the `http://localhost:9999/ui/app/` URL, I only see a blank page with some errors in the console - see the log file: [localhost-1705419896671.log](https://github.com/orthanc-server/orthanc-explorer-2/files/13952947/localhost-1705419896671.log)

What am I missing so that I could make the dev mode work? I've even managed to compile my own version of OE2 plugin (needed to add some different flags than the ones in the README instructions) and it works well, it just takes too long to compile in order for me to be efficient in developing a new feature.

BR,
Nejc

**Comment by amazy** [comment]
Hi,

```
GET http://localhost:9999/ui/api/pre-login-configuration 502 (Bad Gateway)
```
This error message usually indicates that nginx can not access Orthanc so there must be an issue in nginx.  Opening http://localhost:9999/system should show you the content of http://localhost:8042/system.

HTH,

Alain.

**Comment by crocy** [comment]
Hi Alain.

I'll look into nginx, but don't really know what could be the issue, since everything I'm working on is freshly installed. Any hints?

And yes, both of the links you posted work and give the same output:

```
{
   "ApiVersion" : 21,
   "CheckRevisions" : false,
   "DatabaseBackendPlugin" : null,
   "DatabaseServerIdentifier" : "60091f52-aa906407-54d17d22-e250f2e1-f91c97b6",
   "DatabaseVersion" : 6,
   "DicomAet" : "ORTHANC",
   "DicomPort" : 4242,
   "HasLabels" : true,
   "HttpPort" : 8042,
   "IngestTranscoding" : "",
   "IsHttpServerSecure" : true,
   "MainDicomTags" : 
   {
      "Instance" : "0008,0012;0008,0013;0008,0018;0020,0012;0020,0013;0020,0032;0020,0037;0020,0100;0020,4000;0028,0008;0054,1330",
      "Patient" : "0010,0010;0010,0020;0010,0030;0010,0040;0010,1000",
      "Series" : "0008,0021;0008,0031;0008,0060;0008,0070;0008,1010;0008,103e;0008,1070;0018,0010;0018,0015;0018,0024;0018,1030;0018,1090;0018,1400;0020,000e;0020,0011;0020,0037;0020,0105;0020,1002;0040,0254;0054,0081;0054,0101;0054,1000",
      "Study" : "0008,0020;0008,0030;0008,0050;0008,0080;0008,0090;0008,1030;0020,000d;0020,0010;0032,1032;0032,1060"
   },
   "MaximumStorageMode" : "Recycle",
   "MaximumStorageSize" : 0,
   "Name" : "Orthanc",
   "OverwriteInstances" : false,
   "PluginsEnabled" : true,
   "StorageAreaPlugin" : null,
   "StorageCompression" : false,
   "UserMetadata" : {},
   "Version" : "1.12.1"
}
```

**Comment by crocy** [comment]
Hm, actually, the dev mode works now... But now I have the OE2 plugin installed and that might add the `/ui/app` route? I'll check and let you know.

**Comment by crocy** [comment]
Yes, that seems to be the case. If you're working on OE2, you've probably already installed that plugin at some point and so the `npm run dev` mode works as it should. But if you're starting with a clean install and OE2 plugin isn't yet installed, the dev mode won't work because the route `/up/app` isn't recognised. That should be made clear in the README instructions. I'll update them in my PR, but could already be done on the main branch already.

**Comment by amazy** [comment]
Clarified the dev instructions in this commit: https://github.com/orthanc-server/orthanc-explorer-2/commit/8563047f67989add1c0683bc3b90c8bb42a6fee2
