### ISSUE TITLE
OHIF disappeared after #52 fix

### ISSUE THREAD

**Issue by sprog0** [orthanc-server/orthanc-explorer-2#54]
In the mainline version from 04-04-2024 can't see OHIF icons.
Previous version
![image](https://github.com/orthanc-server/orthanc-explorer-2/assets/103747828/c2adba8c-8f17-41d2-add9-0b9661919347)
Current version
![image](https://github.com/orthanc-server/orthanc-explorer-2/assets/103747828/74318cd5-feb4-47c7-b68d-9524e5e74edd)

**Comment by yomarbuzz** [comment]
@amazy I still can't see OHIF button for bulk viewing, might be related.
