### ISSUE TITLE
DateFormat not respected 

### ISSUE THREAD

**Issue by dmd** [orthanc-server/orthanc-explorer-2#55]
I have OrthancExplorer2.UiOptions.DateFormat set in orthanc.json to MM/dd/yyyy. 

This seems to affect only one thing - the Study Date search box. It does **not** affect the "Display format for dates in the study list" (which remains dd/MM/yyyy), even though that is what the comments for that option say it does in https://github.com/orthanc-server/orthanc-explorer-2/blob/master/Plugin/DefaultConfiguration.json 

Finally, it does not affect the format for entering dates when editing DICOM tags (though this is probably to be expected given the date field there is not implemented as date input; it would be nice if it were.)

**Comment by dmd** [comment]
Awesome. When might this hit the orthancteam/orthanc docker release?

**Comment by amazy** [comment]
If the nightly [build succeeds](https://github.com/orthanc-server/orthanc-builder/actions), that should be available in `orthancteam/orthanc-pre-release:master-unstable` tomorrow morning.  That would be great if you could validate it.

Then, I'll probably release an official release within 2 weeks.  [Stay tuned](https://discourse.orthanc-server.org/t/how-to-get-notified-of-new-releases/4425) !

**Comment by dmd** [comment]
The build failed...

**Comment by amazy** [comment]
@dmd some builds have now succeeded.  Could you give it a try to validate ?

**Comment by dmd** [comment]
Tested, works! Thank you!
