### ISSUE TITLE
Search button (or opening URL) makes 2 find request

### ISSUE THREAD

**Issue by sprog0** [orthanc-server/orthanc-explorer-2#57]
For example http://.../ui/app/#/filtered-studies?StudyDate=20240523&ModalitiesInStudy=CT generates (in my case):
first call {"Level":"Study","Limit":500,"Query":{"StudyDate":"20240524"},"RequestedTags":["ModalitiesInStudy"],"Expand":true}
second call {"Level":"Study","Limit":500,"Query":{"StudyDate":"20240524","ModalitiesInStudy":"CT"},"RequestedTags":["ModalitiesInStudy"],"Expand":true}
As we see, first call can be huge and slow and return all studies of the day. Second is all we need.

**Comment by amazy** [comment]
What is your configuration wrt these configurations ?
```
  "StudyListSearchMode": "search-as-you-type",// mode to trigger a search in the StudyList.  Accepted values: 'search-as-you-type' or 'search-button'
  "StudyListSearchAsYouTypeMinChars": 3,      // minimum number of characters to enter in a text search field before it starts searching the DB
  "StudyListSearchAsYouTypeDelay": 400,       // Delay [ms] between the last key stroke and the trigger of the search
  "StudyListContentIfNoSearch": "most-recents", // Defines what to show if no search criteria has been entered
                                                          // Allowed values: "empty", "most-recents"
```

I just tried with the above default config with 1.4.1 and entering this url: http://localhost:8042/ui/app/#/filtered-studies?StudyDate=20210311&ModalitiesInStudy=MR and I'm seeing a single call to `find`.

Same with
```
  "StudyListSearchMode": "search-button",
  "StudyListContentIfNoSearch": "empty"
```
and same with 
```
  "StudyListSearchMode": "search-button",
  "StudyListContentIfNoSearch": "most-recents"
```

There sure are double calls to `tools/find` in some situations but I want to make sure to clearly identify them.

With this config:
```
  "StudyListSearchMode": "search-button",
  "StudyListContentIfNoSearch": "most-recents"
```
If I first open http://localhost:8042/ui/app/#/filtered-studies?StudyDate=20220114 and then, click on 'MR' modalities and click the Search-button, I do see 2 calls to `tools/find` as you describe

**Comment by amazy** [comment]
leaving the issue open until @sprog0 validates on his use case and until I perform a full validation in most common scenarios.

**Comment by sprog0** [comment]
I have the folowing config:
`"StudyListSearchMode": "search-button",
"StudyListContentIfNoSearch": "empty",`
And yes. Start page already filterd by study date. I use a special page for users to open OE2:
`<body onload="d = new Date(); window.location.replace('https://HostName/ui/app/#/filtered-studies?StudyDate=' + (d.getFullYear() * 10000 + (d.getMonth() + 1) * 100 + d.getDate()));">`

**Comment by sprog0** [comment]
Now only one call makes to find, but first of two described above.
After selection of ModalitiesInStudy, URL changed to reflect this, but query containes only date.
Opening "today", chooseing CT, pushing Search. See all today's studies. URL `/ui/app/#/filtered-studies?StudyDate=20240619&ModalitiesInStudy=CT`
Pushing Refresh in browser. Gets only CT. URL `/ui/app/#/filtered-studies?StudyDate=20240619&ModalitiesInStudy=CT`
Pushing Search again. Gets all today's studies anew. URL `/ui/app/#/filtered-studies?StudyDate=20240619&ModalitiesInStudy=CT`
Conclusion. Find query contain ModalitiesInStudy only on full page refresh.

**Comment by amazy** [comment]
@sprog0 can you give it a try again after [this commit](https://github.com/orthanc-server/orthanc-explorer-2/commit/650f6005f1372ea5cef2294e88b3d0d5e0525221) ?

**Comment by sprog0** [comment]
Looks like it's working now
