### ISSUE TITLE
Upload function only uses first file

### ISSUE THREAD

**Issue by dmd** [orthanc-server/orthanc-explorer-2#58]
It's entirely possible I'm doing something wrong, but I am finding that if I use the 'Upload' function in OE2, whether I use 'Select Folder' or 'Select Files', it only actually uploads the *first* file it finds - no matter how many files are in the folder or how many files were selected.

**Comment by amazy** [comment]
Well, I'm ashamed to confirm that you are right !!!!  I'll look into it !
