### ISSUE TITLE
How to display instance count and sending AET?

### ISSUE THREAD

**Issue by radmedics01** [orthanc-server/orthanc-explorer-2#64]
Hallo everybody,

how can we add two additional column, one displaying the instance count of the study - to check if all instances are transfered and the sending AET - to see where the study came from?

Thank you very much for your answer!

**Comment by gdevenyi** [comment]
I'm interesting in adding the same column to the list as well.

**Comment by sprog0** [comment]
Instance count can be seen in the same column as "# series" if you expand the study.
To see the source of study you can add StationName which is configurable on the device and can identify them, or ManufacturerModelName if you don't have multiple identical devices.
The list of columns is in the StudyListColumns parameter in orthanc-explorer-2.json

**Comment by radmedics01** [comment]
Hi,

1. The instances are just per series, i need a sum. When there are 2000 or 3000 instances, you need an additional tool to sum up all the series.
2. I need to know, which "station" delivered us the study, the DICOM data is not the point. We have different DICOM nodes and i want to see which of them send us the instances

**Comment by sprog0** [comment]
![2024-08-28 081558](https://github.com/user-attachments/assets/bc60f145-a7ac-4067-bdc1-b49c6848b4f7)
1. Use /statistics from API menu of a study. This is an additional request, and run it by default will significantly slow down page loading. There is no point in adding it to the regular loading algorithm. CountInstances of the resulting json will show you the total count.
![2024-08-28 082110](https://github.com/user-attachments/assets/26e03654-a001-4abe-be4f-15e5c03137c0)

2. AET information is a part of transfering protocol and can be changed on the way of delivery images to final destination. For example you can use proxy Orthanc servers to accumulate studies on remote location and transfet it to main Orthanc on schduled time. Nevertheless on instance level Orthanc store this information in matadate. To view it, expand study, expand instance, expand frame, in API menu select /metadata?expand, locate RemoteAET in opend json.

**Comment by radmedics01** [comment]
Hi,

ok i understand. Is it possible to modify this menu?

**Comment by sprog0** [comment]
Its inside the source code. See orthanc-explorer-2/WebApplication/src/components
/ResourceButtonGroup.vue

**Comment by amazy** [comment]
@radmedics01 an alternate way to display the RemoteAET is to label incoming studies with the RemoteAET.
Here is a [sample lua script](https://github.com/orthanc-server/orthanc-setup-samples/blob/master/lua-samples/label-incoming-studies.lua) that you could use for that.

Concerning the number of instances, I'll check if we can display it directly in the study list without slowing down the system.

**Comment by amazy** [comment]
[Next version](https://github.com/orthanc-server/orthanc-explorer-2/commit/d4a0fa0fb27c137053056b6597452dd52b5ef206#diff-82200ce47fa528129da57d8979b63119ebdc262e3d07cb7882fdb8d1ecdf4a00) will display both the seriesCount and the instancesCount

![image](https://github.com/user-attachments/assets/4f636ff9-d3e7-476a-9108-b1ef0860b3c8)
